cbx-client-dev:
  triggers:  
    pull_request:
      branches: ["dev"]
  build_args:
    REACT_APP_API_URL: api.dev.councilbox.com
    REACT_APP_CERT_API: secure-api.dev.councilbox.com
  dockerfile: docker/Dockerfile

cbx-client-pre:
  triggers:  
    prerelease:
  build_args:
    REACT_APP_API_URL: api.pre.councilbox.com
    REACT_APP_CERT_API: secure-api.pre.councilbox.com
  dockerfile: docker/Dockerfile

cbx-client-pro:
  triggers:  
    release:
  build_args:
    REACT_APP_API_URL: api.councilbox.com
    REACT_APP_CERT_API: secure-api.councilbox.com
  dockerfile: docker/Dockerfile
