version: '3'

services:
  councilbox-client:
    image: councilbox-client
    build: 
      context: .
      dockerfile: docker/Dockerfile.dev
    env_file:
      - docker/environment/test/env
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/

