FROM node:12-slim

REACT_APP_API_URL=api.pre.councilbox.com
GENERATE_SOURCEMAP=false

RUN apt-get update && apt-get install git -y

COPY docker/entrypoint.sh /entrypoint.sh

WORKDIR /app

CMD [ "/entrypoint.sh" ]
